name: Release

on:
  create:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  create_release:
    name: Pre-Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: create_release
    env:
      libname: NA2202_2203_2204
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Archive
        run: |
          mkdir -p ${{ env.libname }}
          mv  src/ examples/ library.properties keywords.txt LICENSE ${{ env.libname }}
          7z a ${{ env.libname }}_${{ github.ref_name }}.zip ${{ env.libname }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ env.libname }}_${{ github.ref_name }}.zip
          asset_name: ${{ env.libname }}_${{ github.ref_name }}.zip
          asset_content_type: application/zip
